server:
  port: 8100
# 日志配置
logging:
  level:
    com.alibaba.druid.filter.stat.StatFilter: error
spring:
  # 文件上传
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    async:
      request-timeout: 3600000
  #数据库配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/code-helper?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initialSize: 10
      maxActive: 20
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 160000
      maxEvictableIdleTimeMillis: 230000
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      validationQuery: SELECT 1
      validation-query-timeout: 500
      filters: stat,wall
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false               # 开启mybatis的二级缓存
  global-config:
    db-config:
      logic-delete-field: deleted     # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1           # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0       # 逻辑未删除值(默认为 0)